# .github/workflows/docker-deploy.yml

name: Build and Deploy Docker Image

on:
push:
branches:
\- main

jobs:
build\_and\_push:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up QEMU
    uses: docker/setup-qemu-action@v2

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2

  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build and push
    uses: docker/build-push-action@v4
    with:
      context: .
      push: true
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/btc-turbo:latest
```

deploy\_to\_railway:
runs-on: ubuntu-latest
needs: build\_and\_push
steps:
\- name: Trigger Railway Deploy
run: |
curl -X POST&#x20;
-H "Authorization: Bearer \${{ secrets.RAILWAY\_API\_TOKEN }}"&#x20;
-H "Content-Type: application/json"&#x20;
-d '{"serviceId":"\${{ secrets.RAILWAY\_SERVICE\_ID }}","dockerImage":"\${{ secrets.DOCKERHUB\_USERNAME }}/btc-turbo\:latest"}'&#x20;
[https://api.railway.app/v1/deployments](https://api.railway.app/v1/deployments)
